plugins { id 'com.android.application' }

android {
    namespace 'com.rodrigosambade.offlinefirst'
    compileSdk {
        version = release(37) { minorApiLevel = 1 }
    }
    defaultConfig {
        applicationId 'com.rodrigosambade.offlinefirst'
        minSdk 26
        targetSdk 37
        versionCode 1
        versionName '1.0'

    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

}

dependencies {
    implementation "androidx.room:room-runtime:2.8.4"
    annotationProcessor "androidx.room:room-compiler:2.8.4"
    implementation "androidx.work:work-runtime:2.11.2"
}
